SCHEDULE = {
    "2026-04-25": {
        "title": "Ngày 1 — Thứ Sáu 25/04",
        "activities": [
            ("05:00", "Tập trung nhà Hiền"),
            ("05:15", "Di chuyển đến điểm xe khách"),
            ("08:10", "Đến cảng Ao Tiên, lấy vé tàu cao tốc"),
            ("10:30", "Lên tàu đến Quan Lạn"),
            ("11:45", "Đến đảo Quan Lạn"),
            ("12:00", "Check-in chỗ ở, nhận xe máy"),
            ("12:15", "Ăn trưa"),
            ("13:15", "Về home nghỉ ngơi"),
            ("15:30", "Tắm biển"),
            ("17:30", "Về khách sạn tắm rửa, nghỉ"),
            ("18:30", "Ăn tối"),
            ("20:00", "Dạo đảo — café chill hoặc bắt còng đêm"),
            ("22:30", "Về home chơi hoặc nghỉ ngơi"),
        ],
    },
    "2026-04-26": {
        "title": "Ngày 2 — Thứ Bảy 26/04",
        "activities": [
            ("05:00", "Ngắm bình minh bãi Quan Lạn ⚠ Tự nguyện"),
            ("07:00", "Ăn sáng"),
            ("08:00", "Di chuyển đến Minh Châu (~12 km)"),
            ("08:40", "Tắm biển Minh Châu"),
            ("11:30", "Ăn trưa"),
            ("13:30", "Đi bãi Rùa"),
            ("14:45", "Eo Gió Quan Lạn"),
            ("16:15", "Cung đường ven biển Minh Châu"),
            ("17:30", "Về home tắm, nghỉ ngơi"),
            ("19:00", "Ăn tối"),
            ("20:30", "Câu mực hoặc café dạo phố"),
            ("22:30", "Về home nghỉ ngơi"),
        ],
    },
    "2026-04-27": {
        "title": "Ngày 3 — Chủ Nhật 27/04",
        "activities": [
            ("05:00", "Ngắm bình minh đồi Vô Cực ⚠ Tự nguyện"),
            ("07:30", "Ăn sáng"),
            ("08:30", "Đi chợ Quan Lạn mua quà"),
            ("09:30", "Sắp đồ, chuẩn bị checkout"),
            ("10:30", "Ăn trưa và đổi vé về"),
            ("12:00", "Có mặt tại cảng, chuẩn bị lên tàu"),
            ("12:30", "Lên tàu cao tốc về đất liền"),
        ],
    },
}
